### ISSUE TITLE
Working in Progress

### ISSUE THREAD

**Issue by BBCByComcast** [BBCByComcast/iDroid#1]
![Picsart_23-12-16_18-52-36-342](https://github.com/BBCByComcast/iDroid/assets/137778363/85896c0f-ff77-42fa-bd5c-ee01bfb435bc)

iDroid has Working in Progress, Before Launch And Create Brand New iDroid a BBCByComcast Are Acquiring TomJo2000, If You Have See it: https://github.com/iDroid-Project Then iDroid Project has Shutdown So Thanks

Copyright ©iDroid Project
Rightcopy ®HectoByte
Reversed ™BBCByComcast Are Have HectoByte, iDroid Project

**Comment by TomJo2000** [comment]
I have no relevant experience, or desire to run MacOS on Android/Termux.
Please do not contact me about working on this project again.
***Especially*** considering it is currently vaporware,
as you have chosen not to share any of your supposed work on this project.
I'm not gonna make your project for you.

I am a busy person with a full time job, I have neither the time, energy nor motivation
to work on this project, unpaid and in my own free time, for you.

Once again.
Please do not contact me, or other Termux contributors about this again unsolicited.

**Comment by BBCByComcast** [comment]
> I have no relevant experience, or desire to run MacOS on Android/Termux. Please do not contact me about working on this project again. _**Especially**_ considering it is currently vaporware, as you have chosen not to share any of your supposed work on this project. I'm not gonna make your project for you.
> 
> I am a busy person with a full time job, I have neither the time, energy nor motivation to work on this project, unpaid and in my own free time, for you.
> 
> Once again. Please do not contact me, or other Termux contributors about this again unsolicited.

I'm Sorry TomJo2000, I Try New Project is Windroid Than iDroid And I Recontact Yourself

You Cause iDroid Project And I Lead You When I Create New Project, _**Especially**_ Consider Can Run About Windows Without Ubuntu, All Because of That Project, I Do Not Contact TomJo2000 to That Project, Thought I Will Contact TomIO or TomJo2000 When I Create New Project

Please Do Not Give Up to My Another Project, I Need Because Somebody Wanted Windows 11 in Android or Termux, That So True About Sylirre And Twaik, Me Also Acquired HectoByte
